    name: GitHub Classroom Workflow


    on: [push]
    


    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 1.11
              uses: actions/setup-java@v1
              with:
                java-version: 1.11
                
            - uses: actions/checkout@v2
            - uses: maxim-lobanov/setup-android-tools@v1
              with:
                packages: |
                  platforms;android-29
                  platforms;android-30
                  system-images;android-30;google_apis;x86
            
            - name: Build with Gradle
              run: ./gradlew build        
          
            - uses: education/autograding@v1
